import type { Metadata } from "next";
import { inter, nunito } from "@/app/ui/fonts";
import './globals.css';
import Header from "@/app/_components/layouts/header";
import Footer from "@/app/_components/layouts/footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${nunito.variable} ${inter.variable}`}>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <body className="font-body antialiased">
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
